### ISSUE TITLE
ComObject design

### ISSUE THREAD

**Issue by miot** [dx-rs/dx_core#4] opened 2015-06-09 16:53 UTC
Hi there, Mr. Black-Cat-with-a-Tie!
Would you mind to tell me about the design of ComObject, are you happy with it? It feels... verbose, awkward, with all that `impl<TComObject> for TComObject where TComObject : ComObject<...bla-bla> + ISomething` stuff passing around. What do you think?

I'm thinking about an adoption of WinRT for Rust. It is very similar to COM ecosystem, just little differences here and there. And this awkward feeling is really a blocker for me.

Maybe you had some other ideas? Or maybe this all is a matter of compiler plugin, codegen, other tools?

Looking forward to hearing from you, and please excuse me for my English.

**Comment by Mr-Byte** [comment] 2015-06-11 01:39
Hey there!

I originally started out with traits such as `IUnknown: Sized` that had default implementations that did a `transmute` of their self parameter to a pointer to the concrete type to obtain a reference to the `vtable` and to pass as the `this` parameter to the COM method.  I didn't really ever like that design because of the constant need to `transmute` self for every method.  I wound up writing macros to simplify this and had gone down quite a rabbit hole with that, when I realized I was more-so obscuring intent than just getting this project done.

After talking a bit with some other rust users, I would up settling on the `ComObject` design.  Although a bit verbose, it has significantly reduced the amount of unsafe blocks within the code and I've written a couple of macros to really help simplify things down, but without feeling like I've made the code worse in some way.

The current design wound up feeling more ergonomic to me in the long run, as the blanket impls for a particular type, cover any type that implements ComObject for that given type, which I've simplified down with a macro.  The blanket impls are definitely lengthy and a bit unruly, though.  I'm always open to more ideas on how to improve the COM implementation, though!  I've actually been revisiting this to make the `ComRef` smart pointer work in a more idiomatic way for rust.

This could probably definitely be simplified with a compiler plugin or codegen.  I've mostly chosen to implement this by hand at this time as both an exercise in learning more about rust and as a way to more easily cover some of the weird edge cases of DirectX that makes a catch-all code generator a bit harder to write.

**Comment by miot** [comment] 2015-06-11 12:11
Thank you for the thorough explanation!

In fact, at some point I came up with the idea to split your `ComObject` to two separate traits, this helped to simplify/clarify things a bit. You may to see an example [here](https://gist.github.com/miot/73a596618df3ad5811f3). For example,
```
impl<TComObject> IAdapter for TComObject
    where TComObject: ComObject<Adapter, Vtable=AdapterVtable> + IObject { ... }
```
becomes
```
impl<T: HasVtable<Adapter> + IObject> IAdapter for T { ... }
```

In the example you may notice a bunch of empty 'marker' `impl`s that normally should be behind a macro:
```
impl Vtable for SpVoice { type Vtable = SpVoiceVtbl; }

unsafe impl HasVtable<com::abi::Unknown> for SpVoice { }
//unsafe impl HasVtable<SpNotifySource> for SpVoice { }
//unsafe impl HasVtable<SpEventSource> for SpVoice { }
unsafe impl HasVtable<SpVoice> for SpVoice { }
```

Also, I've [posted to reddit](https://www.reddit.com/r/rust/comments/39d2b7/using_windows_com_from_rust_v2/) to gather some feedback, but not so successful as I thought, tbh :) I'm sure you saw already retep998's winapi-rs. He [doesn't use](https://github.com/retep998/winapi-rs/blob/master/src/lib.rs#L139) traits and implements methods directly on 'com objects'. `Deref` emulates inheritance and provides visibility of 'inherited' methods.

BTW, I remembered the [SharpDX project](https://github.com/sharpdx/SharpDX). They are using some sort of [configurable](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.DXGI/Mapping.xml) codegen. Maybe you want a similar approach. Maybe not for DXGI for the reasons aforementioned by you, but for other parts of the DX API.

On a final note, could you explain why do you removed `Clone` from `ComRef`?

Again, please let me know your thoughts.

**Comment by Mr-Byte** [comment] 2015-06-11 14:17
I initially investigated re-purposing the SharpDX generator (I've used and love SharpDX) for this project, but it had gotten a bit tricky because of the way it was developed and some of the dependencies it took.  Since, at the time it was made, there were no IDLs for DirectX the project was designed around scraping the interfaces and flag types out of the headers using gccxml.  The project then used C#'s partial class feature to implement the methods that couldn't be easily code generated.

I started down a similar codegen route using F# and libclang to perform the codegen, but later abandoned that; however I would like to revisit this project, potentially.  The biggest task really is figuring out how to handle the edge cases (which span more than DXGI and into the D3D11 APIs) in a clean way.

As for why I took clone off of `ComRef` was that while investigating the DirectX APIs, it came to my attention that parts were not thread safe, while others were thread safe.  So I removed the clone implementation on `ComRef` to better follow the safety guarantees of rust, as I'm trying to build a safe API over DirectX.  My plan is then to add a clone-like implementation those types that are thread safe, which will return a new `ComRef` for that type.

I'll have to take some time to review both your and win-rs' implementation of COM.  It might be of interest to build a common COM library for both of our projects, but we should probably come up with an implementation that meets both of our needs. :)

**Comment by Mr-Byte** [comment] 2015-06-15 14:01
After looking at it more, I'm going to move in the direction of retep998 and use implementations of `Deref` and `DerefMut` to provide COM functionality.  This greatly reduces the overall boiler plate code needed.  I'm also going to be tweaking the semantics of `ComRef` a bit more based on the discussion on reddit.

Thank you very much for pointing this all out to me! :)

**Comment by Mr-Byte** [comment] 2015-06-15 15:38
Okay, based on some of you work and the work of retep998, I've come up with this prototype:

https://play.rust-lang.org/?gist=326b95f026a821ee436d&version=stable

I feel it's a hybrid between what you've done and what retep998 has done.  I have a `Vtable` trait that has an associated type `Vtable`.  This trait is useful in that it will allow `ComRef` to restrict the types it can hold to those that are `Vtable`.  It also allows you to make the `Vtable` for a given type private to the module, so you're not exposing the nasty details of vtables out to the world.  They only see the type and its associated methods.  The `Deref` is really nice because between it and cross-borrowing, it greatly simplifies code and gets rid of probably 80% of the generics needed in my design.

My final design will implement both `Deref` and `DerefMut` for all COM types, which can be easily done with macros. Depending on the thread safety of given methods, they will have either `&self` or `&mut self` parameters,   This new design also allows you to specify only the direct ancestor of a type, instead of the entirety of the type's ancestry.

I plan to continue not to allow a `Clone` implementation on `ComRef`, but prefer direct implementation of some similar trait (perhaps `AddRef` with `fn add_ref() -> ComRef<RefType>`) that will be implemented directly on the individual types that are safe to create more than one reference to, especially in multi-threaded scenarios.

**Comment by Mr-Byte** [comment] 2015-06-15 16:22
Okay, there were a couple issues on my original gist.  I decided to do a rough prototype of what the new `ComRef` would look like and had to fix some issues.  For instance, the `Vtable` trait wasn't public.  Making it public therefore required making the `Vtable` types also public, which is a shame, but not really a setback.

I've posted an updated gist with a prototype of `ComRef` here: https://play.rust-lang.org/?gist=cfc25a3d6f2f9308fe09&version=stable

Even though the `Vtable` types need to be public, they can be easily marked `#[doc(hidden)]` so users are unaware of them when reading documentation.  I still feel the advantage of a `Vtable` trait is that macros for generating interfaces will need no direct knowledge of the base type's `Vtable` as it can be inferred from the associated type on the `Vtable` trait.

This also demonstrates cross-borrowing a `ComRef<IBaz>` as an `&IFoo`, which works flawlessly.  This design is really starting to shine.

If the RFC regarding using macros in type positions is approved, I'll be able to write a very clean, succinct macro that can generate COM interfaces for all of the usual COM method cases and still allow you to write your own implementations for the more interesting usage scenarios.

I'm thinking the macro would end up looking much like:

```rust
com_interface! {
    interface IUnknown {
        vtable fn query_interface(&mut self, in iid: &IID),
        impl fn add_ref(&mut self),
        impl fn release(&mut self)
    }
    
    impl IUnknown {
        fn query_interface(&mut self) {
            //Implementation goes here!
        }
    }
}
```

Here, the interface allows you to define the type of an interface.  This will generate a vtable for the type given the listing of methods.  Marking a method `vtable` makes it only generate a vtable entry for the method.  Marking it `impl` will attempt to auto-generate a method along with the vtable entry.  Parameters will be marked `in`, `out`, `opt`, etc.  This would mean that the macro could infer the generated parameters and return type of an `impl fn` within the macro, based on the modifiers for a given parameter.  This will really only work in the more simple cases, but it'll really help reduce the amount of code one needs to write, as the vast majority of cases fall into the simple case category.

The `impl` section of a macro then allows you to specify your own implementations of `vtable fn` where you may need to do something that can't be easily generated by the macro.

**Comment by miot** [comment] 2015-06-15 17:36
Wow, thank you for your thorough investigation! This looks nice so far. Also, I'm glad I could help, you're welcome!

However, as my goal is WinRT, I need to do a further investigation. Specifically, I like an example from [ModernCPP](http://moderncpp.com/2015/05/12/when-standard-c-isnt-enough/), please consider:

![image](https://cloud.githubusercontent.com/assets/5273891/8165691/2bf74188-139b-11e5-81b4-c33e3f93210f.png))

What is important here is that `CurrencyFormatter` in fact implements a lot of interfaces. And `ApplyRoundingForCurrency` and `Format` methods come from different non-related interfaces. I.e. `Deref` magic is not able to help here. Nonetheless, there are no **explicit** `QueryInterface` calls!

Desugared standard C++ code looks like:

```
HSTRING_HEADER header = {};
HSTRING string = nullptr;
WindowsCreateStringReference(L"Windows.Globalization.NumberFormatting.CurrencyFormatter", 56, &header, &string);
ICurrencyFormatterFactory * factory = nullptr;
RoGetActivationFactory(string, __uuidof(factory), reinterpret_cast<void **>(&factory));
 
WindowsCreateStringReference(L"USD", 3, &header, &string);
ICurrencyFormatter * currency = nullptr;
factory->CreateCurrencyFormatterCode(string, &currency);
factory->Release();
 
ICurrencyFormatter2 * currency2 = nullptr;
currency->QueryInterface(&currency2);
currency2->ApplyRoundingForCurrency(RoundingAlgorithm_RoundDown);
currency2->Release();
 
INumberFormatter * formatter = nullptr;
currency->QueryInterface(&formatter);
currency->Release();
 
HSTRING result = nullptr;
formatter->FormatDouble(123.456, &result);
formatter->Release();
 
assert(wcscmp(WindowsGetStringRawBuffer(result, nullptr), L"$123.45") == 0);
WindowsDeleteString(result);
```

I think at core it means 'how to abstract out `QueryInterface` calls'. Interesting, does DirectX API have something similar?

---

Maybe one day we will just need to provide a path to idl, and Rust (or Rust compiler plugin) will do everything needed :)

```
compile_idl!("../something.idl");
```

**Comment by Mr-Byte** [comment] 2015-06-15 18:43
DirectX makes more traditional `QueryInterface` calls to get alternate interfaces.  I think a lot of what's going on with WinRT is due in part to the fact that WinRT includes metadata about objects, so the compile is able to infer which interface you meant to call.  DirectX is your much more typical, plain COM.  Although, I am certainly interested in a clean way to do what you're trying to do.

**Comment by Mr-Byte** [comment] 2015-06-15 19:48
The best thing I could come up with is a trait similar to `AsRef` called `AsComRef` that internally calls `QueryInterface` and returns a `ComRef` of the result.  While not as clean as the C++/CX example, it does provide explicit documentation on alternative interfaces implemented by a given type.  The trait looks like:

```rust
pub trait AsComRef<T: Vtable> where Self : Sized {
    fn as_com_ref(&self) -> com_ref::ComRef<T> {
       //Coerce here using QueryInterface and return the result.
    }
}
```

Then implementing it is simply just doing `impl AsComRef<IOther> for IFoo {}`.  You can have multiple implementations, which unfortunately requires type annotations when using, like:

`let other: ComRef<IOther> = foo.as_com_ref();`

Such is the general explicitness of rust, though.  The real benefit to doing this, IMO, is that it provides documentation through rust-doc about what other interfaces a specific type can be coerced to.

**Comment by miot** [comment] 2015-06-16 02:13
> `impl AsComRef<IOther> for IFoo {}`

I think this is not going to work. There are *classes* that hide behind the pointers to interface. Some class `A` may implement both `IFoo` and `IOther`. So we can `QueryInterface` a `&IFoo` to get a `&IOther`. But if we have some class `B` behind a `&IFoo` and class `B` *does not* implement `IOther`, `AsComRef<IOther> for IFoo` will panic.

I have some thoughts that I need to check. WinRT's metadata is a good point. One may use it to provide a lot of information compile-time. Among other things, the necessity of `QueryInterface` before calling some methods.

**Comment by Mr-Byte** [comment] 2015-06-16 20:46
Closing this off for now.  Thanks for the very insightful discussion!

**Closed by Mr-Byte** 2015-06-16 20:46 UTC
